### ISSUE TITLE
html5ever broke API compatibility due to update to 0.8 of markup5ever

### ISSUE THREAD

**Issue by ignatenkobrain** [servo/html5ever#375] opened 2019-05-03 13:39 UTC
I have tried to build `html2pango` which uses html5ever, but it fails:

```rust
BUILDSTDERR: error[E0509]: cannot move out of type `markup5ever::rcdom::RcDom`, which implements the `Drop` trait
BUILDSTDERR:    --> src/lib.rs:335:20
BUILDSTDERR:     |
BUILDSTDERR: 335 |     let document = dom.document;
BUILDSTDERR:     |                    ^^^^^^^^^^^^
BUILDSTDERR:     |                    |
BUILDSTDERR:     |                    cannot move out of here
BUILDSTDERR:     |                    help: consider borrowing here: `&dom.document`
BUILDSTDERR: error[E0509]: cannot move out of type `markup5ever::rcdom::RcDom`, which implements the `Drop` trait
BUILDSTDERR:   --> src/block.rs:38:20
BUILDSTDERR:    |
BUILDSTDERR: 38 |     let document = dom.document;
BUILDSTDERR:    |                    ^^^^^^^^^^^^
BUILDSTDERR:    |                    |
BUILDSTDERR:    |                    cannot move out of here
BUILDSTDERR:    |                    help: consider borrowing here: `&dom.document`
```

This is probably related to https://github.com/servo/html5ever/commit/8bf65ef61daf612a3b4d7e6007fde7297d6210eb#diff-500557afae4b1b1befdebc4eedf9cc09 which has changed API.

Since html5ever is re-exporting markup5ever, it should bump semver when latter is making incompatible changes.

Thanks.

**Comment by jdm** [comment] 2019-05-03 13:43
Duplicate of #373. I'll be addressing the semver issue in #374.

**Closed by jdm** 2019-05-03 13:43 UTC
